// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: persona.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Vaxi {
  public static partial class PersonaService
  {
    static readonly string __ServiceName = "vaxi.PersonaService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Vaxi.PersonaRequest> __Marshaller_vaxi_PersonaRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Vaxi.PersonaRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Vaxi.PersonaResponse> __Marshaller_vaxi_PersonaResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Vaxi.PersonaResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Vaxi.ServerMultiplePersonaRequest> __Marshaller_vaxi_ServerMultiplePersonaRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Vaxi.ServerMultiplePersonaRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Vaxi.ServerMultiplePersonaResponse> __Marshaller_vaxi_ServerMultiplePersonaResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Vaxi.ServerMultiplePersonaResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Vaxi.ClientMultiplePersonaRequest> __Marshaller_vaxi_ClientMultiplePersonaRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Vaxi.ClientMultiplePersonaRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Vaxi.ClientMultiplePersonaResponse> __Marshaller_vaxi_ClientMultiplePersonaResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Vaxi.ClientMultiplePersonaResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Vaxi.BidireccionalPersonaRequest> __Marshaller_vaxi_BidireccionalPersonaRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Vaxi.BidireccionalPersonaRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Vaxi.BidireccionalPersonaResponse> __Marshaller_vaxi_BidireccionalPersonaResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Vaxi.BidireccionalPersonaResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Vaxi.PersonaRequest, global::Vaxi.PersonaResponse> __Method_RegistroPersona = new grpc::Method<global::Vaxi.PersonaRequest, global::Vaxi.PersonaResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RegistroPersona",
        __Marshaller_vaxi_PersonaRequest,
        __Marshaller_vaxi_PersonaResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Vaxi.ServerMultiplePersonaRequest, global::Vaxi.ServerMultiplePersonaResponse> __Method_RegistroPersonaServidorMultiple = new grpc::Method<global::Vaxi.ServerMultiplePersonaRequest, global::Vaxi.ServerMultiplePersonaResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "RegistroPersonaServidorMultiple",
        __Marshaller_vaxi_ServerMultiplePersonaRequest,
        __Marshaller_vaxi_ServerMultiplePersonaResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Vaxi.ClientMultiplePersonaRequest, global::Vaxi.ClientMultiplePersonaResponse> __Method_RegistroPersonaClienteMultiple = new grpc::Method<global::Vaxi.ClientMultiplePersonaRequest, global::Vaxi.ClientMultiplePersonaResponse>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "RegistroPersonaClienteMultiple",
        __Marshaller_vaxi_ClientMultiplePersonaRequest,
        __Marshaller_vaxi_ClientMultiplePersonaResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Vaxi.BidireccionalPersonaRequest, global::Vaxi.BidireccionalPersonaResponse> __Method_RegistroPersonaBidireccional = new grpc::Method<global::Vaxi.BidireccionalPersonaRequest, global::Vaxi.BidireccionalPersonaResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "RegistroPersonaBidireccional",
        __Marshaller_vaxi_BidireccionalPersonaRequest,
        __Marshaller_vaxi_BidireccionalPersonaResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Vaxi.PersonaReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PersonaService</summary>
    [grpc::BindServiceMethod(typeof(PersonaService), "BindService")]
    public abstract partial class PersonaServiceBase
    {
      /// <summary>
      ///gRPC Unary
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Vaxi.PersonaResponse> RegistroPersona(global::Vaxi.PersonaRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///gRPC Server Streaming
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task RegistroPersonaServidorMultiple(global::Vaxi.ServerMultiplePersonaRequest request, grpc::IServerStreamWriter<global::Vaxi.ServerMultiplePersonaResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///gRPC Client Streaming
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Vaxi.ClientMultiplePersonaResponse> RegistroPersonaClienteMultiple(grpc::IAsyncStreamReader<global::Vaxi.ClientMultiplePersonaRequest> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///gRPC Bidireccional Streaming
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task RegistroPersonaBidireccional(grpc::IAsyncStreamReader<global::Vaxi.BidireccionalPersonaRequest> requestStream, grpc::IServerStreamWriter<global::Vaxi.BidireccionalPersonaResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PersonaService</summary>
    public partial class PersonaServiceClient : grpc::ClientBase<PersonaServiceClient>
    {
      /// <summary>Creates a new client for PersonaService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public PersonaServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PersonaService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public PersonaServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected PersonaServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected PersonaServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///gRPC Unary
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Vaxi.PersonaResponse RegistroPersona(global::Vaxi.PersonaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RegistroPersona(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///gRPC Unary
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Vaxi.PersonaResponse RegistroPersona(global::Vaxi.PersonaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RegistroPersona, null, options, request);
      }
      /// <summary>
      ///gRPC Unary
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Vaxi.PersonaResponse> RegistroPersonaAsync(global::Vaxi.PersonaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RegistroPersonaAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///gRPC Unary
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Vaxi.PersonaResponse> RegistroPersonaAsync(global::Vaxi.PersonaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RegistroPersona, null, options, request);
      }
      /// <summary>
      ///gRPC Server Streaming
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Vaxi.ServerMultiplePersonaResponse> RegistroPersonaServidorMultiple(global::Vaxi.ServerMultiplePersonaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RegistroPersonaServidorMultiple(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///gRPC Server Streaming
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Vaxi.ServerMultiplePersonaResponse> RegistroPersonaServidorMultiple(global::Vaxi.ServerMultiplePersonaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_RegistroPersonaServidorMultiple, null, options, request);
      }
      /// <summary>
      ///gRPC Client Streaming
      /// </summary>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::Vaxi.ClientMultiplePersonaRequest, global::Vaxi.ClientMultiplePersonaResponse> RegistroPersonaClienteMultiple(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RegistroPersonaClienteMultiple(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///gRPC Client Streaming
      /// </summary>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::Vaxi.ClientMultiplePersonaRequest, global::Vaxi.ClientMultiplePersonaResponse> RegistroPersonaClienteMultiple(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_RegistroPersonaClienteMultiple, null, options);
      }
      /// <summary>
      ///gRPC Bidireccional Streaming
      /// </summary>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::Vaxi.BidireccionalPersonaRequest, global::Vaxi.BidireccionalPersonaResponse> RegistroPersonaBidireccional(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RegistroPersonaBidireccional(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///gRPC Bidireccional Streaming
      /// </summary>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::Vaxi.BidireccionalPersonaRequest, global::Vaxi.BidireccionalPersonaResponse> RegistroPersonaBidireccional(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_RegistroPersonaBidireccional, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override PersonaServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PersonaServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(PersonaServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_RegistroPersona, serviceImpl.RegistroPersona)
          .AddMethod(__Method_RegistroPersonaServidorMultiple, serviceImpl.RegistroPersonaServidorMultiple)
          .AddMethod(__Method_RegistroPersonaClienteMultiple, serviceImpl.RegistroPersonaClienteMultiple)
          .AddMethod(__Method_RegistroPersonaBidireccional, serviceImpl.RegistroPersonaBidireccional).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PersonaServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_RegistroPersona, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Vaxi.PersonaRequest, global::Vaxi.PersonaResponse>(serviceImpl.RegistroPersona));
      serviceBinder.AddMethod(__Method_RegistroPersonaServidorMultiple, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Vaxi.ServerMultiplePersonaRequest, global::Vaxi.ServerMultiplePersonaResponse>(serviceImpl.RegistroPersonaServidorMultiple));
      serviceBinder.AddMethod(__Method_RegistroPersonaClienteMultiple, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::Vaxi.ClientMultiplePersonaRequest, global::Vaxi.ClientMultiplePersonaResponse>(serviceImpl.RegistroPersonaClienteMultiple));
      serviceBinder.AddMethod(__Method_RegistroPersonaBidireccional, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::Vaxi.BidireccionalPersonaRequest, global::Vaxi.BidireccionalPersonaResponse>(serviceImpl.RegistroPersonaBidireccional));
    }

  }
}
#endregion
